# If you see me, please update my `rev` field using the provided links
# Click the repo and update to latest tags.
# If things break on update, raise an issue
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort imports mfpbench
        files: mfpbench

      - id: isort
        name: isort imports tests
        files: tests

  - repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
      - id: black
        name: black formatter mfpbench
        files: mfpbench

      - id: black
        name: black formatter tests
        files: tests

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        name: mypy
        files: mfpbench/.*

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        name: flake8 src
        files: mfpbench/.*

      - id: flake8
        name: flake8 test
        files: tests/.*



  #- repo: https://github.com/pycqa/pydocstyle
  # rev: 6.1.1
  # hooks:
  #   - id: pydocstyle
  #     files: mfpbench
  #     additional_dependencies: ["toml"] # Needed to parse pyproject.toml
