name: docs
on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ubuntu-latest-${{ env.pythonLocation }}-${{hashFiles('pyproject.toml')}}
      - run: pip install ".[dev]"
      - run: git config --local user.name "docs-bot"
      - run: git config --local user.email "docs-bot@automl.org"
      - run: mike deploy ${{ github.ref_name }} latest --force --push --update-aliases
      - run: mike set-default --push --force latest
