name: docs

on:
  # Trigger manually
  workflow_dispatch:

  # Trigger on any push to the main
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache

      - run: pip install ".[dev]"
      - run: git config --local user.name "docs-bot"
      - run: git config --local user.email "docs-bot@automl.org"
      - run: mike deploy ${{ github.ref_name }} latest --push --update-aliases
      - run: mike set-default --push latest
