name: Tests
on:
  # Allow to manually trigger through github API
  workflow_dispatch:
  # Triggers with push to main
  push:
    branches:
      - main
      - development
  # Triggers with push to a PR aimed at main
  pull_request:
    branches:
      - main
      - development
jobs:
  # General unit tests
  source-test:
    name: ${{ matrix.python-version }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{matrix.os}}-${{ env.pythonLocation }}-${{hashFiles('pyproject.toml')}}
      - run: python -m pip install -e ".[dev]"
      - run: pytest -vvs
