name: Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
jobs:
  source-test:
    name: ${{ matrix.python-version }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{matrix.os}}-${{ env.pythonLocation }}-${{hashFiles('pyproject.toml')}}
      - run: python -m pip install -e ".[dev]"
      - run: pytest -vvs
