name: Tests

on:
  # Allow to manually trigger through github API
  workflow_dispatch:

  # Triggers with push to main
  push:
    branches:
      - main
      - development

  # Triggers with push to a PR aimed at main
  pull_request:
    branches:
      - main
      - development

env:

  package-name: mfpbench

  # Arguments used for pytest
  pytest-args: >-
    --durations=20
    -v

jobs:

  # General unit tests
  source-test:
    name: ${{ matrix.python-version }}-${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash # Default to using bash on all

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - run: python -m pip install -e ".[dev]"
    - run: pytest ${{ env.pytest-args }}
